spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://dpg-crungs5umphs7385c9b0-a.oregon-postgres.render.com/my_postgres_cloud_server
    username: my_postgres_cloud_server_user 
    password: 7VEKpIYfZVILq8OZQziGTVL8OivaNooF
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create  # or 'create', 'create-drop', depending on your use case
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8099

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
